[package]
name = "day03"
version = "0.1.0"
authors = ["Jeff Bradberry <jeff.bradberry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
counter = "0.4.3"
itertools = "0.8.1"